apiVersion: v1
kind: Pod
metadata:
  name: guestbook-test-pod
  labels:
    app: guestbook-test
spec:
  containers:
    - name: nginx
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
