apiVersion: v1
kind: Pod
metadata:
  name: guestbook-test-pod
  annotations: 
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app: guestbook-test
spec:
  containers:
    - name: nginx
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80